name: media_library
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
  dio: ^4.0.0
  video_player: ^2.2.6
  just_audio: ^0.9.17
  epub_viewer: ^0.2.4
  file_picker: ^4.2.2+1

dev_dependencies:
  build_runner: ^2.1.4

  json_serializable:

flutter:
  uses-material-design: true

  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf
    - family: IPix
      fonts:
        - asset: assets/fonts/IPix.ttf

  assets:
    - assets/json/pokemon/
    - assets/json/video/
    - assets/json/music/
    - assets/json/book/
    - assets/pic/
    - assets/book/
