# access token request
POST https://accounts.spotify.com/api/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic e3efd9bed6eb4ea690f1854d69be5110:31e3e1cb3b4c4a719fcafd47a6eb6de9

grant_type=client_credentials

# {"access_token":"BQDzWKTgefka3oOBxbZ0017EA_bUN5VoDD_waXeCy3VRYiIwp0yWsyi0gdC-ZsWUGHezlVGQBbiL2iAoWBA","token_type":"Bearer","expires_in":3600}

### search(type:album)
GET https://api.spotify.com/v1/search
  ?type=album
  &q=artist:One%20ok%20rock
  &include_external=audio  
Authorization: Bearer BQCDdz4z8zRy2LtBQMqReVD9MnAYenDV7BlJcM7lj_Gf3Q3Z2j6lp3aMYrflsbnAcVvFJfBjhZgm_u34kYg
Content-Type: application/json

### album tracks
GET https://api.spotify.com/v1/albums/0p1YL9nzIuKTonZH6Gq58i/tracks
Authorization: Bearer BQCDdz4z8zRy2LtBQMqReVD9MnAYenDV7BlJcM7lj_Gf3Q3Z2j6lp3aMYrflsbnAcVvFJfBjhZgm_u34kYg

### album image
GET https://i.scdn.co/image/ab67616d0000b273794179deeade79ef08eabd94